language: java
install: true

jdk:
  - oraclejdk8
 
addons:
  sonarcloud:
    organization: "sriharisahu-github"
    token:
      secure: 65846feaf88d067a79011788d9cc1f7fde76bb1a
  artifacts: true

script:
  - ./gradlew build test dependencyCheckAnalyze sonarqube